version: "3.8"
services:
  db:
    image: mongo
    volumes:
      - data:/data/db
    env_file:
      - .env
  app:
    build: ./
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - image:/app/public/thumbnail
      - ./:/app
      - /app/node_modules

volumes:
  data:
  image: